<?php

namespace AppBundle\Repository;

/**
 * EvaluationExamenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationExamenRepository extends \Doctrine\ORM\EntityRepository
{
}
