<?php

namespace AppBundle\Repository;

/**
 * EvaluationEnsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationEnsRepository extends \Doctrine\ORM\EntityRepository
{
}
