<?php

namespace AppBundle\Repository;

/**
 * MoyennesMatieresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoyennesMatieresRepository extends \Doctrine\ORM\EntityRepository
{
}
